# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Task.destroy_all
Review.destroy_all

User.create({name: "Dr. A Zee", bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", role: "counselor", image: "https://s3.amazonaws.com/onename/avatar-placeholder.png", status: "offline"})

User.create({name: "Dr. E Bee", bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vulputate eu scelerisque felis imperdiet proin. Nec nam aliquam sem et tortor. At tellus at urna condimentum mattis. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Diam maecenas ultricies mi eget. Adipiscing elit pellentesque habitant morbi tristique senectus. Aliquet risus feugiat in ante metus dictum at. Odio facilisis mauris sit amet. Purus faucibus ornare suspendisse sed nisi lacus. Erat nam at lectus urna. At augue eget arcu dictum varius duis at consectetur. Ac felis donec et odio pellentesque diam volutpat commodo sed. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. In nibh mauris cursus mattis molestie a iaculis at. Dictum at tempor commodo ullamcorper a lacus vestibulum. Iaculis nunc sed augue lacus viverra. Dictumst quisque sagittis purus sit amet volutpat consequat.", role: "counselor", image: "https://s3.amazonaws.com/onename/avatar-placeholder.png", status: "offline"})

User.create({name: "Dr. W Laa", bio: "Amet dictum sit amet justo donec enim diam vulputate ut. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet. Feugiat vivamus at augue eget arcu dictum varius duis. Accumsan tortor posuere ac ut consequat semper viverra nam. Enim blandit volutpat maecenas volutpat blandit aliquam. Et malesuada fames ac turpis egestas integer. Amet nisl purus in mollis. In pellentesque massa placerat duis ultricies lacus sed turpis. In tellus integer feugiat scelerisque varius morbi enim. Et ligula ullamcorper malesuada proin libero nunc consequat. Felis imperdiet proin fermentum leo vel orci porta non. Diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Arcu dui vivamus arcu felis bibendum ut tristique et egestas. Elementum nisi quis eleifend quam adipiscing vitae. Diam maecenas sed enim ut sem viverra aliquet eget sit. Semper viverra nam libero justo laoreet sit amet cursus. Sit amet cursus sit amet. Vel quam elementum pulvinar etiam non quam lacus. Enim eu turpis egestas pretium aenean pharetra magna ac placerat.", role: "counselor", image: "https://s3.amazonaws.com/onename/avatar-placeholder.png", status: "offline"})

User.create({name: "Dr. T Mii", bio: "Cursus turpis massa tincidunt dui ut ornare lectus. Sit amet consectetur adipiscing elit pellentesque. Magna fringilla urna porttitor rhoncus dolor purus. Condimentum mattis pellentesque id nibh tortor id aliquet lectus proin. Diam vel quam elementum pulvinar etiam non. Mollis aliquam ut porttitor leo a diam sollicitudin. Tincidunt eget nullam non nisi est sit. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Id cursus metus aliquam eleifend mi in nulla. Scelerisque varius morbi enim nunc faucibus.", role: "counselor", image: "https://s3.amazonaws.com/onename/avatar-placeholder.png", status: "offline"})

User.create({name: "Dr. Y Muu", bio: "Arcu vitae elementum curabitur vitae nunc. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Lacus viverra vitae congue eu consequat. Euismod quis viverra nibh cras pulvinar mattis. Ullamcorper sit amet risus nullam eget felis eget nunc lobortis. Donec enim diam vulputate ut pharetra. Vitae congue eu consequat ac felis. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ornare quam viverra orci sagittis eu volutpat odio. In nulla posuere sollicitudin aliquam. Sociis natoque penatibus et magnis. Gravida in fermentum et sollicitudin. Ultricies integer quis auctor elit sed vulputate mi. Sit amet nisl purus in mollis.", role: "counselor", image: "https://s3.amazonaws.com/onename/avatar-placeholder.png", status: "offline"})

User.create({name: "Tony L", bio: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?", role: "patient", image: "https://s3.amazonaws.com/onename/avatar-placeholder.png", status: "offline"})

Task.create({counselor_id: 1, patient_id: 6, task: "Go to the corner store once a day.", complete: true })
Task.create({counselor_id: 1, patient_id: 6, task: "Call a friend for 5 minutes.", complete: true })
Task.create({counselor_id: 1, patient_id: 6, task: "Meet a friend for coffee.", complete: false })
Task.create({counselor_id: 1, patient_id: 6, task: "Talk to a mutual friend of a friend.", complete: false })